### ISSUE TITLE
Add config + regexp support

### ISSUE THREAD

**Issue by dead-claudia** [dead-claudia/journald-exporter#10]
Here's the idea: TOML-based config. CLI parameters take precedence but all become optional with sensible defaults if you pass a `--config path/to/config.toml`. And entries can be monitored for via specified filters.

For the config, I'm thinking something like this, idiomatically located at `/etc/journald-exporter/config.toml`:

```toml
# These are defaults if not specified.
[global]
port = 12345
key_dir = '/etc/journald-exporter/keys'

# These are defaults if not specified.
[https]
certificate = '/etc/journald-exporter/cert.key'
private_key = '/etc/journald-exporter/priv.key'

# Omitting a field allows everything. Any number of these can be specified,
# as long as they have different key names (`foo_info` for this example).
# The name can be anything, even the empty string.
[monitor.foo_info]
service = 'foo.service' # String, matches whole service
                        # If the `.unit` type is omitted, `.service` is assumed
priority = 'info'       # Syslog priority keyword as string, case-insensitive
                        # Deprecated aliases and raw severity numbers are also
                        # accepted.
user = 'foo'            # User, both strings, UIDs, and `?` strings are accepted
group = 'foo'           # Group, both strings, GIDs, and `?` strings are accepted
message = 'reg.*exp'    # Rust regular expression to match the message against

# Another example
[monitor.bar_err]
service = 'bar.service'
priority = 'err'
message = '3\d\d'
```

And for the metrics, each `key_name` above will be reflected in a pair of new counters: `journald_monitor_hits` for the number of hits and `journald_monitor_hits_bytes` for the number of bytes for each hit. They will have all the same fields as `journald_messages_ingested{,_bytes}`, but with an extra `name` that corresponds to their given `key_name` above.

Also, a `journald-exporter -c config.toml`/`journald-exporter --check config.toml` would be useful to check config validity before deploying it.
